---
dist: xenial
language: python
python: "3.7"
sudo: required
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
script:
  - pipenv run molecule test --scenario-name=mysql
  - pipenv run molecule test --scenario-name=mariadb

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
